# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testnew.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
from PyQt5.QtCore import pyqtSlot
import os
from preprocessing import *
from PyQt5.QtWidgets import QFileDialog, QVBoxLayout, QLabel, QListWidgetItem, QListWidget, QAbstractItemView
import arrayfire as af
import filters_arrayfire as at
import numpy as np
from preprocessing import create_img_window


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.counter = 0
        self.window_name = 'Image'
        self.init_img_path = None
        self.colored_img_arr = None
        self.active_img = None
        self.adjusted_img_array = None
        self.adjusted_img_array_prev = None
        self.save_dir = None
        self.selected_imgs_paths = []
        self.initial_img_arr = None
        self.used_filters = {"current": [], "last": []}
        # *********************** IMPORT / EXPORT list **********************************
        self.filters = {"gb_width": {}, "gb_height": {}, "gb_sigma": {}, "it_type": {}, "it_method": {},
                        "it_max_value": {}, "it_threshold": {}, "it_block_size": {}, "it_c_value": {},
                        "ce_threshold_1": {}, "ce_threshold_2": {}, "dil_width": {}, "dil_height": {},
                        "dil_iterations": {}, "ero_width": {}, "ero_height": {}, "ero_iterations": {}}
        self.json_loaded_filters = {}
        self.qlist = None
        self.filters2 = {}
        self.json_loaded_filters2 = {}
        self.select_filter_window = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 161, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_selectimgs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_selectimgs.setObjectName("btn_selectimgs")
        self.verticalLayout.addWidget(self.btn_selectimgs)
        self.btn_saveimgs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_saveimgs.setObjectName("btn_saveimgs")
        self.verticalLayout.addWidget(self.btn_saveimgs)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 791, 31))
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(170, 40, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.radioBtn_orig = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioBtn_orig.setObjectName("radioBtn_orig")
        self.verticalLayout_2.addWidget(self.radioBtn_orig)
        self.radioBtn_prep = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioBtn_prep.setObjectName("radioBtn_prep")
        self.verticalLayout_2.addWidget(self.radioBtn_prep)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(420, 240, 181, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_undo = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_undo.setObjectName("btn_undo")
        self.verticalLayout_3.addWidget(self.btn_undo)
        self.btn_reset = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_reset.setObjectName("btn_reset")
        self.verticalLayout_3.addWidget(self.btn_reset)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(650, 350, 221, 341))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 201, 311))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.vs_gb_height = QtWidgets.QSlider(self.verticalLayoutWidget_8)
        self.vs_gb_height.setMaximum(15)
        self.vs_gb_height.setOrientation(QtCore.Qt.Vertical)
        self.vs_gb_height.setObjectName("vs_gb_height")
        self.gridLayout_5.addWidget(self.vs_gb_height, 1, 2, 1, 1)
        self.vs_gb_width = QtWidgets.QSlider(self.verticalLayoutWidget_8)
        self.vs_gb_width.setMaximum(15)
        self.vs_gb_width.setOrientation(QtCore.Qt.Vertical)
        self.vs_gb_width.setObjectName("vs_gb_width")
        self.gridLayout_5.addWidget(self.vs_gb_width, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 3, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_5)
        self.btn_gaus = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.btn_gaus.setObjectName("btn_gaus")
        self.verticalLayout_8.addWidget(self.btn_gaus)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 350, 251, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 231, 311))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_method = QtWidgets.QComboBox(self.verticalLayoutWidget_9)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")

        self.horizontalLayout_3.addWidget(self.comboBox_method)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vs_it_block_size = QtWidgets.QSlider(self.verticalLayoutWidget_9)
        self.vs_it_block_size.setMaximum(81)
        self.vs_it_block_size.setOrientation(QtCore.Qt.Vertical)
        self.vs_it_block_size.setObjectName("vs_it_block_size")
        self.gridLayout_2.addWidget(self.vs_it_block_size, 1, 0, 1, 1)
        self.vs_it_c_value = QtWidgets.QSlider(self.verticalLayoutWidget_9)
        self.vs_it_c_value.setMaximum(80)
        self.vs_it_c_value.setOrientation(QtCore.Qt.Vertical)
        self.vs_it_c_value.setObjectName("vs_it_c_value")
        self.gridLayout_2.addWidget(self.vs_it_c_value, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 4, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.btn_threshold = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.btn_threshold.setObjectName("btn_threshold")
        self.verticalLayout_9.addWidget(self.btn_threshold)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 360, 131, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 111, 301))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vs_ce_threshold_1 = QtWidgets.QSlider(self.verticalLayoutWidget_7)
        self.vs_ce_threshold_1.setMaximum(500)
        self.vs_ce_threshold_1.setOrientation(QtCore.Qt.Vertical)
        self.vs_ce_threshold_1.setObjectName("vs_ce_threshold_1")
        self.gridLayout_3.addWidget(self.vs_ce_threshold_1, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.btn_canny = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.btn_canny.setObjectName("btn_canny")
        self.verticalLayout_7.addWidget(self.btn_canny)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(170, 360, 231, 331))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 20, 191, 301))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 1, 3, 1, 1)
        self.vs_kernel_width = QtWidgets.QSlider(self.verticalLayoutWidget_6)
        self.vs_kernel_width.setMaximum(15)
        self.vs_kernel_width.setOrientation(QtCore.Qt.Vertical)
        self.vs_kernel_width.setObjectName("vs_kernel_width")
        self.gridLayout_4.addWidget(self.vs_kernel_width, 1, 0, 1, 1)
        self.vs_kernel_height = QtWidgets.QSlider(self.verticalLayoutWidget_6)
        self.vs_kernel_height.setMaximum(15)
        self.vs_kernel_height.setOrientation(QtCore.Qt.Vertical)
        self.vs_kernel_height.setObjectName("vs_kernel_height")
        self.gridLayout_4.addWidget(self.vs_kernel_height, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_erosion = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.btn_erosion.setObjectName("btn_erosion")
        self.horizontalLayout_2.addWidget(self.btn_erosion)
        self.btn_dilat = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.btn_dilat.setObjectName("btn_dilat")
        self.horizontalLayout_2.addWidget(self.btn_dilat)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(420, 150, 181, 81))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_importparams = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_importparams.setObjectName("btn_importparams")
        self.verticalLayout_4.addWidget(self.btn_importparams)
        self.btn_exportparams = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_exportparams.setObjectName("btn_exportparams")
        self.verticalLayout_4.addWidget(self.btn_exportparams)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 150, 401, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listWidget.setDragDropMode(QAbstractItemView.InternalMove)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_applyall = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_applyall.setObjectName("btn_applyall")
        self.verticalLayout_11.addWidget(self.btn_applyall)
        self.btn_applyselected = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_applyselected.setObjectName("btn_applyselected")
        self.verticalLayout_11.addWidget(self.btn_applyselected)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 121, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 22))
        self.menubar.setObjectName("menubar")
        self.menuPreprocessing_app = QtWidgets.QMenu(self.menubar)
        self.menuPreprocessing_app.setObjectName("menuPreprocessing_app")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPreprocessing_app.menuAction())

        self.retranslateUi(MainWindow)
        self.vs_gb_width.valueChanged['int'].connect(self.label_7.setNum)
        self.vs_gb_height.valueChanged['int'].connect(self.label_8.setNum)
        self.vs_ce_threshold_1.valueChanged['int'].connect(self.label_20.setNum)
        self.vs_kernel_width.valueChanged['int'].connect(self.label_24.setNum)
        self.vs_kernel_height.valueChanged['int'].connect(self.label_25.setNum)
        self.vs_it_c_value.valueChanged['int'].connect(self.label_17.setNum)
        self.vs_it_block_size.valueChanged['int'].connect(self.label_13.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # *********************** SETUP BTNS CLICKED ********************8
        self.btn_selectimgs.clicked.connect(lambda: self.getFileNames())
        self.btn_saveimgs.clicked.connect(lambda: self.save_active_img())
        self.btn_undo.clicked.connect(lambda: self.undo_last_change())
        self.btn_reset.clicked.connect(lambda: self.reset_image())
        self.btn_exportparams.clicked.connect(lambda: self.export_params())
        self.btn_importparams.clicked.connect(lambda: self.import_params())
        self.btn_dilat.clicked.connect(lambda: self.apply_morph("dilation", 0, 0, False))
        self.btn_erosion.clicked.connect(lambda: self.apply_morph("erosion", 0, 0, False))
        self.btn_gaus.clicked.connect(lambda: self.apply_gaussian_blur(0, 0, False))
        self.btn_canny.clicked.connect(lambda: self.apply_canny_edge(0, False))
        self.btn_threshold.clicked.connect(lambda: self.apply_threshold(int(0), int(0), int(0), False))
        self.radioBtn_orig.clicked.connect(lambda: self.change_img_preview(1))
        self.radioBtn_prep.clicked.connect(lambda: self.change_img_preview(2))
        self.btn_applyselected.clicked.connect(lambda: self.apply_selected_filter(self.listWidget.currentItem().text()))
        self.btn_applyall.clicked.connect(lambda: self.apply_filters_from_listWidget_to_img(self.listWidget))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_selectimgs.setText(_translate("MainWindow", "Select images"))
        self.btn_saveimgs.setText(_translate("MainWindow", "Save images"))
        self.label.setText(_translate("MainWindow", "Preprocessing application"))
        self.label_2.setText(_translate("MainWindow", "Preview mode"))
        self.radioBtn_orig.setText(_translate("MainWindow", "Original"))
        self.radioBtn_prep.setText(_translate("MainWindow", "Preprocessed"))
        self.btn_undo.setText(_translate("MainWindow", "Undo"))
        self.btn_reset.setText(_translate("MainWindow", "Reset"))
        self.groupBox.setTitle(_translate("MainWindow", "Gaussian Blur"))
        self.label_5.setText(_translate("MainWindow", "Width"))
        self.label_3.setText(_translate("MainWindow", "Height"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.btn_gaus.setText(_translate("MainWindow", "Apply"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Image Thresholding"))
        self.label_4.setText(_translate("MainWindow", "Method :"))
        self.comboBox_method.setItemText(0, _translate("MainWindow", "Method1"))
        self.comboBox_method.setItemText(1, _translate("MainWindow", "Method2"))
        self.comboBox_method.setItemText(2, _translate("MainWindow", "Method3"))
        #self.comboBox_2.setItemText(3, _translate("MainWindow", "To Zero"))
       # self.comboBox_2.setItemText(4, _translate("MainWindow", "To Zero Inverse"))
       # self.comboBox_2.setItemText(5, _translate("MainWindow", "Otsu"))
       # self.comboBox_2.setItemText(6, _translate("MainWindow", "Triangle"))
        self.label_13.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "Block size"))
        self.label_17.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "C value"))
        self.btn_threshold.setText(_translate("MainWindow", "Apply"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Canny Edge"))
        self.label_22.setText(_translate("MainWindow", "Threshold 1"))
        self.label_20.setText(_translate("MainWindow", "0"))
        self.btn_canny.setText(_translate("MainWindow", "Apply "))
        self.groupBox_4.setTitle(_translate("MainWindow", "Dilate / Erode"))
        self.label_25.setText(_translate("MainWindow", "1"))
        self.label_28.setText(_translate("MainWindow", "Height"))
        self.label_27.setText(_translate("MainWindow", "Width"))
        self.label_24.setText(_translate("MainWindow", "1"))
        self.btn_erosion.setText(_translate("MainWindow", "Erosion"))
        self.btn_dilat.setText(_translate("MainWindow", "Dilatation"))
        self.btn_importparams.setText(_translate("MainWindow", "IMPORT PARAMS"))
        self.btn_exportparams.setText(_translate("MainWindow", "EXPORT PARAMS"))
        self.btn_applyall.setText(_translate("MainWindow", "APPLY ALL"))
        self.btn_applyselected.setText(_translate("MainWindow", "APPLY SELECTED"))
        self.label_6.setText(_translate("MainWindow", "Imported filters"))
        self.menuPreprocessing_app.setTitle(_translate("MainWindow", "Preprocessing app"))


# ********************************** FUNCTIONS FOR BUTTONS *****************************************


    def getFileNames(self):
        filter = 'Data File (*.jpeg *.jpg *.tif);; Picture File (*.jpeg *.jpg)'
        response = QFileDialog.getOpenFileNames(
            parent=MainWindow,
            caption='Select a data file',
            directory=os.getcwd(),
            filter=filter,
        )
        if response:
            self.selected_imgs_paths = response[0]
            self.adjusted_img_array_prev = None
            self.image = cv2.imread(self.selected_imgs_paths[0])
            self.used_filters['current'] = []
            self.used_filters['last'] = []
            self.set_colored_img(self.image)
            self.set_grayscale_img(self.image)

            create_img_window(680, 700, 'Image')

            cv2.imshow(self.window_name, self.active_img)

        print(self.selected_imgs_paths)

    def set_initial_img(self, init_img_path):
        self.selected_imgs_paths = [init_img_path]
        self.initial_img_arr = cv2.imread(init_img_path)
        self.set_colored_img(self.initial_img_arr)
        self.set_grayscale_img(self.colored_img_arr)
        self.imgs_selected_text.set(f"Number of selected images: "
                                    f"{len(self.selected_imgs_paths)}")

    def change_img_preview(self, mod):
        if mod == 1:
            self.active_img = self.colored_img_arr
            cv2.imshow(self.window_name, self.active_img)
        if mod == 2:
            self.active_img = self.adjusted_img_array
            cv2.imshow(self.window_name, self.active_img)

    def undo_last_change(self):
        if self.adjusted_img_array_prev is not None:
            tmp_adj_img_array = self.adjusted_img_array
            self.adjusted_img_array = self.adjusted_img_array_prev
            self.adjusted_img_array_prev = tmp_adj_img_array
            tmp_current_filters = self.used_filters['current'].copy()
            self.used_filters['current'] = self.used_filters['last'].copy()
            self.used_filters['last'] = tmp_current_filters
        if self.radioBtn_prep.isChecked():
            self.active_img = self.adjusted_img_array
        cv2.imshow(self.window_name, self.active_img)

    def reset_image(self):
        self.adjusted_img_array_prev = self.adjusted_img_array
        self.used_filters['last'] = self.used_filters['current'].copy()
        self.set_grayscale_img(self.colored_img_arr)
        self.used_filters['current'] = self.used_filters['current'][0:1]
        if self.radioBtn_prep.isChecked():
            self.active_img = self.adjusted_img_array
        cv2.imshow(self.window_name, self.active_img)

    def set_colored_img(self, new_img_arr):
        self.colored_img_arr = new_img_arr
        self.active_img = self.colored_img_arr

    def set_grayscale_img(self, new_colored_img_arr):
        grayscale_fn = lambda img_array: cv2.cvtColor(img_array,
                                                      cv2.COLOR_BGR2GRAY)
        self.adjusted_img_array = grayscale_fn(new_colored_img_arr)
        self.used_filters['last'] = self.used_filters['current'].copy()
        self.used_filters['current'].append(grayscale_fn)

    def apply_morph(self, morph, width, height, imported):
        self.adjusted_img_array_prev = self.adjusted_img_array
        if (imported == True):
            kernel_width = width
            kernel_height = height
            #iterations = 0
        else:
            kernel_width = int(self.vs_kernel_width.value())
            kernel_height = int(self.vs_kernel_height.value())
            #iterations = 0
        #kernel = np.ones((kernel_height, kernel_width), np.uint8)
        kernel = af.np_to_af_array(np.ones((kernel_height, kernel_width), np.uint8))
        if morph == "erosion":
            self.filters2[str(self.counter)] = {"erosion": {"width": kernel_width, "height": kernel_height}}
            self.filters.get("ero_width")[str(self.counter)] = kernel_width
            self.filters.get("ero_height")[str(self.counter)] = kernel_height
            erosion_fn = lambda img_array: \
                af.image.erode(img_array, kernel)
            self.adjusted_img_array = af.Array.to_ndarray(erosion_fn(af.np_to_af_array(self.adjusted_img_array)))
            self.used_filters['last'] = self.used_filters['current'].copy()
            self.used_filters['current'].append(erosion_fn)
        elif morph == "dilation":
            self.filters2[str(self.counter)] = {"dilation": {"width": kernel_width, "height": kernel_height}}
            self.filters.get("dil_width")[str(self.counter)]=kernel_width
            self.filters.get("dil_height")[str(self.counter)]=kernel_height
            dilation_fn = lambda img_array: \
                af.image.dilate(img_array, mask=kernel)
            self.adjusted_img_array = af.Array.to_ndarray(dilation_fn(af.np_to_af_array(self.adjusted_img_array)))
            self.used_filters['last'] = self.used_filters['current'].copy()
            self.used_filters['current'].append(dilation_fn)
        self.update_img()
        cv2.imshow(self.window_name, self.active_img)
        self.counter += 1

    def update_img(self):
        self.active_img = self.adjusted_img_array

    def apply_canny_edge(self, threshold1, imported):
        self.adjusted_img_array_prev = self.adjusted_img_array
        if not imported:
            threshold1 = int(self.vs_ce_threshold_1.value())
        self.filters2[self.counter] = {"canny edge": {"threshold 1": threshold1}}
        self.filters.get("ce_threshold_1")[str(self.counter)] = threshold1
        canny_fn = lambda img_array: cv2.Canny(img_array, threshold1, threshold2)
        cv2.imwrite('save.jpg', self.adjusted_img_array)
        af_img = af.image.load_image('save.jpg', True)
        im = at.adaptive_canny(af_img, threshold1/100)
        af.image.save_image(im, 'save.jpg')
        self.adjusted_img_array = cv2.imread('save.jpg', 1)
        self.used_filters['last'] = self.used_filters['current'].copy()
        self.used_filters['current'].append(canny_fn)
        self.update_img()
        cv2.imshow(self.window_name, self.active_img)
        self.counter += 1
        # todo mode_choice

    def apply_threshold(self, th_method, it_block_size, it_c_value, imported):
        # Mean adaptive th. = 0
        # Median adaptive th. = 1
        # Min Max Average adaptive th = 2
        self.adjusted_img_array_prev = self.adjusted_img_array
        if not imported:
            th_method = int(self.comboBox_method.currentIndex())
            it_block_size = int(self.vs_it_block_size.value())
            it_c_value = int(self.vs_it_c_value.value())
        self.filters2[self.counter] = {"image thresholding": {"method": th_method,
                                                              "block size": it_block_size,
                                                              "c value": it_c_value}}
        self.filters["it_method"][str(self.counter)] = th_method
        self.filters["it_block_size"][str(self.counter)] = it_block_size
        self.filters["it_c_value"][str(self.counter)] = it_c_value
        af.set_backend('cpu') #todo it can be deleted but macs openCL doesnt support doubles
        cv2.imwrite('save.jpg', self.adjusted_img_array)
        af_img = af.image.load_image('save.jpg', True)
        im = at.adaptive_threshold(af_img, th_method, it_block_size, it_c_value)
        self.adjusted_img_array = af.Array.to_ndarray(im)
        # otsu
        th_type = 0
        if th_type == 5:
            th_type = 8
        # triangle
        elif th_type == 6:
            th_type = 16
        # if pixel has higher than threshold value = pixel will be 255 (white)
        if th_type == 0 or th_type == 1:
            at_fn = lambda img_array: \
                cv2.adaptiveThreshold(img_array, it_max_value,
                                      th_method, th_type,
                                      it_block_size,
                                      it_c_value)
        else:
            at_fn = lambda img_array: \
                cv2.threshold(img_array, int(self.vs_it_threshold.value()),
                              it_max_value, cv2.THRESH_BINARY + th_type)
        self.update_img()
        self.used_filters['last'] = self.used_filters['current'].copy()
        self.used_filters['current'].append(at_fn)
        cv2.imshow(self.window_name, self.active_img)
        self.counter += 1

    def apply_gaussian_blur(self, width, height, imported):
        self.adjusted_img_array_prev = self.adjusted_img_array
        if (imported == True):
            kernel_width = width
            kernel_height = height
        else:
            kernel_width = int(self.vs_gb_width.value())
            kernel_height = int(self.vs_gb_height.value())
        self.filters2[str(self.counter)] = {"gaussian blur": {"width": kernel_width, "height": kernel_height}}
        self.filters["gb_width"][str(self.counter)] = kernel_width
        self.filters["gb_height"][str(self.counter)] = kernel_height
        gb_fn = lambda img_array: \
            cv2.GaussianBlur(img_array, (kernel_width, kernel_height), sigma)
        cv2.imwrite('save.jpg', self.adjusted_img_array)
        af_img = af.image.load_image('save.jpg', True)
        im = at.adaptive_gaussian(af_img, kernel_height, kernel_width)
        af.image.save_image(im, 'save.jpg')
        self.adjusted_img_array = cv2.imread('save.jpg', 1)
        self.used_filters['last'] = self.used_filters['current'].copy()
        self.used_filters['current'].append(gb_fn)
        self.update_img()
        cv2.imshow(self.window_name, self.active_img)
        self.counter += 1

    def import_params(self):
        self.read_json()
        list_from_json = self.json_to_list()
        for item in list_from_json:
            self.listWidget.addItem(item)

    def read_json(self):
        filter2 = 'Data File (*.json)'
        response = QFileDialog.getOpenFileName(
            parent=MainWindow,
            caption='Select a data file',
            directory=os.getcwd(),
            filter=filter2,
        )
        if response:
            with open(response[0]) as file:
                self.json_loaded_filters2 = json.load(file)

    def json_to_list(self):
        strings = []
        for item in self.json_loaded_filters2.values():
            string = ""
            for filter in item:
                string += str(filter) + ", params: "
                for param in item.get(filter):
                    string += str(param) + " = " + str(item.get(filter).get(param)) + ", "
                strings.append(string)
                print(string)
        return strings

    def set_sel_param(self, param):
        self.sel_param = param


    def export_params(self):
        path = QFileDialog.getExistingDirectory(
            self,
            caption='Select a folder'
        )
        print(self.filters2)
        json_filters2 = json.dumps(self.filters2)
        path += "\\filters2.json"
        file = open(path, "w")
        file.write(json_filters2)
        file.close()

    def save_active_img(self):
        preprocessed_imgs = []
        path = QFileDialog.getExistingDirectory(
            self,
            caption='Select a folder'
        )
        c = 0
        for img_filename in self.selected_imgs_paths:
            preprocessed = self.apply_filters_to_img(img_filename)
            preprocessed_imgs.append(preprocessed)
            a = img_filename.split('/')
            image_name = a[-1]
            name_list = image_name.split('.')
            name = name_list[0]
            result = af.image.save_image(preprocessed, path + "/" + name + "_PREPROCESSED.jpg")
            if result == True:
                print("Files saved successfully")
            else:
                print("Files saved unsuccessfully")
            c += 1

    def apply_filters_to_img(self, img_path):
        img = af.image.load_image(img_path, True)
        filt = self.filters2
        for number in filt:
            for filter in filt[number]:
                name = filt[number][filter]
                if (filter == "gaussian blur"):
                    width = name["width"]
                    height = name["height"]
                    img = at.adaptive_gaussian(img, height, width)
                if (filter == "erosion"):
                    width = name["width"]
                    height = name["height"]
                    kernel = af.np_to_af_array(np.ones((height, width), np.uint8))
                    img = af.image.erode(img, kernel)
                if (filter == "dilation"):
                    width = name["width"]
                    height = name["height"]
                    kernel = af.np_to_af_array(np.ones((height, width), np.uint8))
                    img = af.image.dilate(img, mask=kernel)
                if (filter == "canny edge"):
                    threshold1 = name["threshold 1"]
                    img = at.adaptive_canny(img, threshold1 / 100)
                if (filter == "image thresholding"):
                    method = name["method"]
                    block_size = name["block size"]
                    c_value = name["c value"]
                    img = at.adaptive_threshold(img, int(method or 0), int(block_size or 0), int(c_value or 0))
        return img

    def apply_filters_from_listWidget_to_img(self, object):
        c = object.count()
        for i in range(c):
            item = object.item(i).text()
            self.apply_selected_filter(item)


    def apply_selected_filter(self, item):
        arr = []
        for s in item.split():
            s = s.replace(',', '')
            if s.isdigit():
                arr.append(int(s))
        if "gaussian blur" in item:
            width = arr[0]
            height = arr[1]
            self.apply_gaussian_blur(width, height, True)
        if "erosion" or "dilation" in item:
            width = arr[0]
            height = arr[1]
            self.apply_morph(item, width, height, True)
        if "canny edge" in item:
            threshold1 = arr[1]
            self.apply_canny_edge(threshold1, True)
        if "image thresholding" in item:
            method = arr[0]
            block_size = arr[1]
            c_value = arr[2]
            self.apply_threshold(int(method or 0), int(block_size or 0), int(c_value or 0), True)


    def apply_selected_filter_from_import(self):
        self.sel_param = self.select_filter_window.get_selected_filter()
        selected =self.json_loaded_filters2.get(str(self.sel_param))
        for filter in selected:
            if (filter == "gaussian blur"):
                width = selected.get(filter).get("width")
                height = selected.get(filter).get("height")
                self.apply_gaussian_blur(width,height,True)
            if (filter == "erosion" or filter == "dilation"):
                width = selected.get(filter).get("width")
                height = selected.get(filter).get("height")
                self.apply_morph(filter,width,height,True)
            if (filter == "canny edge"):
                threshold1 = selected.get(filter).get("threshold 1")
                self.apply_canny_edge(threshold1,True)
            if (filter == "image thresholding"):
                method = selected.get(filter).get("method")
                block_size = selected.get(filter).get("block size")
                c_value = selected.get(filter).get("c value")
                self.apply_threshold(int(method or 0), int(block_size or 0), int(c_value or 0), True)


    def create_img_window(width=680, height=700, name='Image'):
        cv2.namedWindow(name, cv2.WINDOW_NORMAL | cv2.WINDOW_KEEPRATIO)
        cv2.resizeWindow(name, width, height)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
